- pom.xml
- src/main/java/org/dataone/hashstore/filehashstore/FileHashStore.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStorePublicTest.java
FileHashStore has been refactored to initialize via a configuration file `hashstore.yaml` in a given store path. It no longer allows a null store path (no default directories) and the calling app must explicitly declare where it intends the store to exist.
- Upon instantiation, it will check for the existence of `hashstore.yaml`.
- If found, it compares the given properties to ensure that it matches the existing configuration.
- If not found, it will check for the existence of HashStore at the given store path (objects and directories).
- If there are objects, it will raise an exception that the configuration file is missing.
Once the properties have been verified, it will proceed to initialize with the given properties, ensuring consistent usage of the existing store.
**New Methods:**
- …
> Feature-24: FileHashStore Configuration

- src/main/java/org/dataone/hashstore/HashStore.java
- src/main/java/org/dataone/hashstore/exceptions/PidObjectExistsException.java
- src/main/java/org/dataone/hashstore/filehashstore/FileHashStore.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStoreInterfaceTest.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStoreProtectedTest.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStorePublicTest.java
- Added new `PidObjectExistsException` to be thrown when pid object to store already exists & updated tests.
- Resolved catching exceptions that already covered by their super classes in `storeObject`, resolving most of the warnings (`There is a more general exception, ..., in the throws list already`)
- `PidObjectExistsException` is left there intentionally to improve debugging issues (even though it is covered by `IOException`)
- Cleaned up code for readability and fixed minor bugs
> Feature-20: Customized Exceptions

- src/main/java/org/dataone/hashstore/HashStore.java
- src/main/java/org/dataone/hashstore/filehashstore/FileHashStore.java
- src/test/java/org/dataone/hashstore/HashStoreTest.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStoreInterfaceTest.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStoreProtectedTest.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStorePublicTest.java
- src/test/java/org/dataone/hashstore/testdata/TestDataHarness.java
- Implement `storeMetadata()`Public API method in `FileHashStore`  (plus other supporting protected methods)
- Add junit tests to ensure all new methods are behaving as expected, including confirming that header and body sections are correctly written and that calling `storeMetadata()` on the same `hash(id+formatId)` only writes one file in total without any collisions (pid synchronization)
- Bug fix and updated junit tests for `storeObject` where `checksumAlgorithm` is supplied but never utilized in `writeToTmpFileAndGenerateChecksums`
> Feature-11: storeMetadata Public API method

- .idea/misc.xml
- src/main/java/org/dataone/hashstore/HashAddress.java
- src/main/java/org/dataone/hashstore/HashStore.java
- src/main/java/org/dataone/hashstore/HashStoreFactory.java
- src/main/java/org/dataone/hashstore/filehashstore/FileHashStore.java
- src/test/java/org/dataone/hashstore/HashAddressTest.java
- src/test/java/org/dataone/hashstore/HashStoreTest.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStoreInterfaceTest.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStoreProtectedTest.java
- Add public API methods `deleteObject`, `deleteMetadata` and `getHexDigest` plus new junit tests
- Refactor `HashAddress` absPath member to be Path object instead of String, added `final` access modifier to all members, and updated all affected junit tests
> Feature-29: Add 'deleteObject', 'deleteMetadata' and 'getHexDigest' Public API Methods

- src/main/java/org/dataone/hashstore/HashStore.java
- src/main/java/org/dataone/hashstore/ObjectMetadata.java
- src/main/java/org/dataone/hashstore/filehashstore/FileHashStore.java
- src/test/java/org/dataone/hashstore/HashStoreTest.java
- src/test/java/org/dataone/hashstore/ObjectMetadataTest.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStoreInterfaceTest.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStoreProtectedTest.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStorePublicTest.java
- src/test/java/org/dataone/hashstore/testdata/TestDataHarness.java
- Refactored `HashAddress` to `ObjectMetadata` and update all junit tests
- Added new attribute to `ObjectMetadata` for size and validating when an expected object size is provided
- Overloaded `storeObject` method to remove usage of `null` when calling method and to allow for convenient calls to specifically validate object size, compare checksums and generate an additional hex digest/hash
- Overloaded `storeMetadata`, `retrieveMetadata` and `deleteMetadata` to enable calling of methods with default store metadata namespace (`formatId`) value
- Small refactor for `loadHashStoreYaml` to reference enum values rather than use specific strings for the keys when creating the HashMap object
> Feature-41: Refactor Hashaddress & Overload Methods

- README.md
- pom.xml
- src/main/java/org/dataone/hashstore/Client.java
- src/main/java/org/dataone/hashstore/HashStore.java
- src/main/java/org/dataone/hashstore/filehashstore/FileHashStore.java
- src/test/java/org/dataone/hashstore/ClientTest.java
- src/test/java/org/dataone/hashstore/testdata/TestDataHarness.java
- Add new java class `Client.java` and respective test class `ClientTest.java`
- Add new dependency to parse arguments from the command line `Apache Commons CLI`
- Revise `pom.xml` to allow packaging of Java project via mvn shade to execute Client code: `mvn clean package -Dmaven.test.skip=true`
- Add functionality to work with a HashStore directly through the java client
- Add functionality to query knbvm's metacat db and convert metacat data/documents into HashStore objects/metadata
- Note: Users must manually create a `pgdb.yaml` file at store path in order to connect to the metacat db
- Updated `README.md` with instructions on how to use client app
- Revise comments and fix bugs in `FileHashStore` and `HashStore` for method override options
> Feature-39: HashStore-java Client App

- pom.xml
- src/main/java/org/dataone/hashstore/filehashstore/FileHashStore.java
- src/main/java/org/dataone/hashstore/filehashstore/FileHashStoreUtility.java
- src/test/java/org/dataone/hashstore/HashStoreTest.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStoreInterfaceTest.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStoreProtectedTest.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStorePublicTest.java
- Added code to delete tmpFile when storeObject is interrupted and when JVM crashes/exits unexpectedly.
- Cleaned up test classes for redundant code.
- Bump up maven-surefire-version plugin (mvn test)
> Feature-49: TmpFile Clean-up

- CONTRIBUTING.md
was copying this for another project, and noticed some leftover python refs
> Bugfix docs python refs

- src/main/java/org/dataone/hashstore/filehashstore/FileHashStore.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStoreInterfaceTest.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStoreProtectedTest.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStorePublicTest.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStoreReferencesTest.java
- Renamed `refs/pid/` and `refs/cid/` directories to `refs/pids/` and `refs/cids/
- Updated junit tests
> Feature-60: Rename `refs` subdirectories

- src/main/java/org/dataone/hashstore/HashStore.java
- src/main/java/org/dataone/hashstore/filehashstore/FileHashStore.java
- Storing and deleting metadata is now synchronized based on the doc name (hash of the `pid+formatId`)
- `deleteObject` now calls `deleteMetadata` instead of retrieving the document names from the metadata directory
> Feature-61: Metadata API Thread Safety

- src/main/java/org/dataone/hashstore/HashStore.java
- src/main/java/org/dataone/hashstore/exceptions/NonMatchingChecksumException.java
- src/main/java/org/dataone/hashstore/exceptions/NonMatchingObjSizeException.java
- src/main/java/org/dataone/hashstore/exceptions/UnsupportedHashAlgorithmException.java
- src/main/java/org/dataone/hashstore/filehashstore/FileHashStore.java
- src/test/java/org/dataone/hashstore/HashStoreClientTest.java
- src/test/java/org/dataone/hashstore/HashStoreRunnable.java
- src/test/java/org/dataone/hashstore/HashStoreTest.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStoreInterfaceTest.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStoreProtectedTest.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStorePublicTest.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStoreReferencesTest.java
- Calling `verifyObject` no longer returns a boolean, but throws custom exception classes when:
- A given `checksum` does not match what has been calculated
- A given `size` does not match what has been calculated
- A `checksumAlgorithm` is not supported
- `verifyObject` now attempts to calculate the `checksum` for a given `checksumAlgorithm` if it is supported and is not part of the default hexDigests map
> Feature-65: `verifyObject` Update

- README.md
- src/main/java/org/dataone/hashstore/HashStoreFactory.java
- src/main/java/org/dataone/hashstore/filehashstore/FileHashStore.java
- src/test/java/org/dataone/hashstore/HashStoreClientTest.java
- src/test/java/org/dataone/hashstore/HashStoreTest.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStoreInterfaceTest.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStoreProtectedTest.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStorePublicTest.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStoreReferencesTest.java
- Updated the init process to check for the existence of specific conflicting `HashStore` directories (objects, metadata and refs) rather than any folder or files when throwing an exception
- Updated junit test classes to improve clarity around `storePath` and the correct metadata namespace for sysmeta documents.
- Updated README.md
> Feature-69: `HashStore` Initialization Improvements

- pom.xml
- Added new `outputFile` and `outputDirectory` settings to `pom.xml` for `maven-shade-plugin` under `<configuration>`
- `hashstore-1.0.jar` is generated with just the `HashStore-java` library
- `hashstore-1.0-shaded.jar` is generated with the dependencies
> Feature-67: `HashStore` .jar File Update

- src/main/java/org/dataone/hashstore/HashStore.java
- src/main/java/org/dataone/hashstore/HashStoreClient.java
- src/main/java/org/dataone/hashstore/ObjectMetadata.java
- src/main/java/org/dataone/hashstore/filehashstore/FileHashStore.java
- src/test/java/org/dataone/hashstore/HashStoreClientTest.java
- src/test/java/org/dataone/hashstore/HashStoreRunnable.java
- src/test/java/org/dataone/hashstore/HashStoreTest.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStoreInterfaceTest.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStoreProtectedTest.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStoreReferencesTest.java
- src/test/java/org/dataone/hashstore/testdata/TestDataHarness.java
- `findObject` now returns a map that contains the following keys:
- cid
- cid_object_path
- cid_refs_path
- pid_refs_path
- sysmeta_path
- HashStore interface has been updated for `findObject`
- Update junit tests
- Clean up `TestDataHarness` for ambiguity with values
> Feature-72: `findObject` Update

- src/main/java/org/dataone/hashstore/filehashstore/FileHashStore.java
- Refactored `tagObject` to replace boolean variables with direct method calls in if-else block. This change reduces the risk of a `cid refs file` being accidentally overwritten due to specific threading conditions.
- Minor comment revisions
- Note: Branch name should have begun with `bug` or `bugfix` 🥲
> Bug-75: `tagObject` Cid Refs File Safety

- src/main/java/org/dataone/hashstore/exceptions/HashStoreRefsAlreadyExistException.java
- src/main/java/org/dataone/hashstore/exceptions/HashStoreServiceException.java
- src/main/java/org/dataone/hashstore/exceptions/PidRefsFileExistsException.java
- src/main/java/org/dataone/hashstore/filehashstore/FileHashStore.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStoreReferencesTest.java
- `tagObject` throws a new custom exception `HashStoreRefsAlreadyExistException` when called to tag files that are already correctly tagged (instead of logging a warning).
> Feature-74: `tagObject` Refs File Already Exists

- src/main/java/org/dataone/hashstore/HashStore.java
- src/main/java/org/dataone/hashstore/HashStoreClient.java
- src/main/java/org/dataone/hashstore/filehashstore/FileHashStore.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStoreInterfaceTest.java
- Removed unused `storeObject` overload methods, updated junit tests and `HashStore` interface
- Fixed `HashStoreClient` error (was calling an overload method)
> Feature-82: Remove unused `storeObject` overload methods

- src/main/java/org/dataone/hashstore/filehashstore/FileHashStoreUtility.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStoreInterfaceTest.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStoreProtectedTest.java
- Supplied `pid` or string arguments are now also checked for illegal characters, and an exception is thrown if found
- Apply auto formatting to junit test classes 'FileHashStoreProtectedTest' and 'FileHashSToreInterfaceTest'
> Feature-81: Safeguard `pid` for Illegal Characters

- README.md
- src/main/java/org/dataone/hashstore/HashStore.java
- src/main/java/org/dataone/hashstore/HashStoreClient.java
- src/main/java/org/dataone/hashstore/filehashstore/FileHashStore.java
- src/test/java/org/dataone/hashstore/HashStoreRunnable.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStoreInterfaceTest.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStoreProtectedTest.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStoreReferencesTest.java
- Updated `verifyObject` signature to include a new boolean value `deleteInvalidObject`
- When set to true, it will attempt to remove the data object directly (safeguards in place)
- Removed Public API method `deleteObject(String, String)` which was leaking implementation details
- Replaced `getExpectedPath` method with three distinct methods:
- `getHashStoreDataObjectPath`, `getHashStoreMetadataPath`, `getHashStoreRefsPath`
- Initially, I kept adding to this `getExpectedPath` as I felt it was the right place to do it - but after reviewing, too much was happening here. If a related-issue occurred, it would not be clear/easy to debug.
- Updated `HashStore` interface javadocs
- `junit` tests have been updated
> Feature-80: 'verifyObject' Signature Update

- src/main/java/org/dataone/hashstore/exceptions/PidRefsFileNotFoundException.java
- src/main/java/org/dataone/hashstore/filehashstore/FileHashStore.java
- src/test/java/org/dataone/hashstore/HashStoreRunnable.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStoreInterfaceTest.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStoreReferencesTest.java
- `tagObject` now has guard rails in place to revert the tagging process
- Added new methods `storeHashStoreRefsFiles`, `unTagObject`
- New junit tests have been added
> Feature-83: `tagObject` Refactor

- src/main/java/org/dataone/hashstore/filehashstore/FileHashStore.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStoreInterfaceTest.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStoreProtectedTest.java
- Reworked the `storeObject` routine to be more efficient by creating objects only when necessary, removing redundant logging statements, and revising variable names for clarity
- Reactivated failing junit test, added additional details to logging statements and revised affected junit test variables to assist with debugging
> Bug-88: `tmpFile` Cleanup

- README.md
- src/main/java/org/dataone/hashstore/HashStore.java
- src/main/java/org/dataone/hashstore/filehashstore/FileHashStore.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStoreInterfaceTest.java
- Renamed Public API method `verifyObject to `deleteInvalidObject`
- Updated the `hashstore` interface and junit tests
> Feature-92: Rename `verifyObject` to `deleteInvalidObject`

- src/main/java/org/dataone/hashstore/filehashstore/FileHashStore.java
- src/main/java/org/dataone/hashstore/hashstoreconverter/FileHashStoreLinks.java
- src/main/java/org/dataone/hashstore/hashstoreconverter/HashStoreConverter.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStoreInterfaceTest.java
After further investigation, it appears that a bug was introduced when optimizing how the default hash algorithms were calculated.
The junit test did its job and threw a new unexpected exception `PidRefsFileExistsException`: which is thrown when the `pid` that has already been accounted for is referencing another `cid`.
This can be observed where multiple instances of unexpected hash calculations were produced, for example:
```
RETRIEVED CID: faa2d37dee00163152f1f13492ab8e29a97407f06b253ee9e916add7caae578e
PROVIDED CID: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```
This specific junit test should only encounter two types of exceptions:
- `RunTimeException` which is thrown when the `pid` is already being stored (synchronization rejects)
- …
> Bug-98: `storeObject` Failed Junit Test

- src/main/java/org/dataone/hashstore/hashstoreconverter/HashStoreConverter.java
- src/test/java/org/dataone/hashstore/hashstoreconverter/FileHashStoreLinksTest.java
- HashStoreConverter's `convert` method now specifically declares that a `NonMatchingChecksumException` will be thrown if there is a mismatch
- Added new junit test & apply auto-formatting to junit test class
> Feature-101: 'NonMatchingChecksumException' Declaration

- src/main/java/org/dataone/hashstore/exceptions/IdentifierNotLockedException.java
- src/main/java/org/dataone/hashstore/filehashstore/FileHashStore.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStoreProtectedTest.java
- `unTagObject` has been extracted from `tagObject` and is now triggered by the actual calling method `storeHashStoreRefsFiles` which may run into an exception and necessitates the call
- `unTagObject`'s synchronization has been removed, and in place of, new guard rails to ensure that the identifiers (pid, cid) are locked before proceeding
- This will throw a new custom exception (to ensure thread safety): `IdentifierNotLockedException`
- Synchronization methods' access modifiers were changed from private to protected to assist with testing
- junit tests have been updated
> Bug-97: `tagObject` Produces Orphaned Object

- pom.xml
- src/main/java/org/dataone/hashstore/filehashstore/FileHashStoreUtility.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStoreInterfaceTest.java
- src/test/java/org/dataone/hashstore/filehashstore/FileHashStoreProtectedTest.java
- FileHashStoreUtility's `generateTmpFile` method now sets default permissions on each temporary file generated (`rw- r-- ---`)
- Added new junit tests to confirm permissions are set and persist
> Feature-108: Default Permissions on HashStore Objects
